# Generated by Django 5.0 on 2023-12-14 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SajilotantraApp', '0002_governmentprofile_guidance'),
        ('SajilotantraApp', '0002_notification'),
    ]

    operations = [
    ]
