# Generated by Django 4.2.7 on 2023-12-15 05:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SajilotantraApp', '0003_merge_20231214_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentprofile',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notice_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
