# Generated by Django 4.2.5 on 2023-12-14 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SajilotantraApp', '0003_merge_20231214_1040'),
        ('SajilotantraApp', '0003_rename_events_event'),
    ]

    operations = [
    ]
