# Generated by Django 4.2.5 on 2023-12-14 14:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SajilotantraApp', '0004_merge_20231214_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentprofile',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notice_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
