# Generated by Django 4.2.7 on 2023-12-16 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SajilotantraApp', '0002_governmentprofile'),
        ('SajilotantraApp', '0005_alter_governmentprofile_description_and_more'),
    ]

    operations = [
    ]
