# Generated by Django 4.2.7 on 2023-12-19 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SajilotantraApp', '0004_alter_governmentprofile_description_and_more'),
        ('SajilotantraApp', '0006_merge_20231216_1638'),
    ]

    operations = [
    ]
