# Generated by Django 5.0 on 2023-12-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SajilotantraApp', '0006_alter_governmentprofile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentprofile',
            name='thumbnail',
            field=models.ImageField(upload_to='static/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='guidance',
            name='thumbnail',
            field=models.ImageField(upload_to='static/thumbnails/'),
        ),
    ]
