# Generated by Django 5.0 on 2023-12-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SajilotantraApp', '0007_alter_governmentprofile_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governmentprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='governmentprofile',
            name='profile_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
