# Generated by Django 4.2.5 on 2023-12-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SajilotantraApp', '0007_alter_event_end_alter_event_start'),
        ('SajilotantraApp', '0009_alter_governmentprofile_profile_id'),
    ]

    operations = [
    ]
