# Generated by Django 5.0 on 2023-12-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SajilotantraApp', '0009_alter_governmentprofile_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
