# Generated by Django 4.2.7 on 2023-12-22 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SajilotantraApp', '0006_merge_20231216_1638'),
        ('SajilotantraApp', '0009_alter_governmentprofile_profile_id'),
    ]

    operations = [
    ]
