# Generated by Django 4.2.6 on 2024-01-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SajilotantraApp', '0010_merge_20231222_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
