# Generated by Django 5.0 on 2023-12-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SajilotantraApp', '0010_alter_guidance_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governmentprofile',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='governmentprofile',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
