# Generated by Django 4.2.7 on 2023-12-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SajilotantraApp', '0011_alter_guidance_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governmentprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='governmentprofile',
            name='profile_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='governmentprofile',
            name='thumbnail',
            field=models.ImageField(upload_to='static/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='guidance',
            name='thumbnail',
            field=models.ImageField(upload_to='static/thumbnails/'),
        ),
    ]
