# Generated by Django 5.0 on 2023-12-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SajilotantraApp', '0011_remove_governmentprofile_profile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
