# Generated by Django 5.0 on 2024-01-09 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SajilotantraApp', '0011_alter_governmentprofile_description_and_more'),
        ('SajilotantraApp', '0012_alter_governmentprofile_id'),
    ]

    operations = [
    ]
