# Generated by Django 5.0 on 2024-01-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SajilotantraApp', '0014_feedback_post_postcomment_postlike_uploadedfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentprofile',
            name='profile_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
