# Generated by Django 4.2.7 on 2024-01-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SajilotantraApp', '0014_reportedpost_userprofile_forget_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover',
            field=models.ImageField(blank=True, default='static/assets/images/default_cover.png', upload_to='static/cover_images/'),
        ),
    ]
